export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDER_FAIL";

export const  CLEAR_ERRORS= "CLEAR_ERRORS";